name: frontend
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: MontserratAlternates
      fonts:
        - asset: assets/fonts/MontserratAlternates-Regular.ttf
        - asset: assets/fonts/MontserratAlternates-Italic.ttf
          style: italic
        - asset: assets/fonts/MontserratAlternates-Bold.ttf
          weight: 700

  assets:
    - assets/images/icons/HalykLifeIcon.svg
  
